### ISSUE TITLE
OS X failing - no "plugins" relation

### ISSUE THREAD

**Issue by johnbowdenatfacet** [owtf/owtf#1016]
I have cloned the repo run the `make startdb` successfully and now trying to install owtf with `python setup.py develop` with the following output:
```
Traceback (most recent call last):
  File "setup.py", line 12, in <module>
    from owtf import __version__
  File "/development/cyber/owtf/owtf/__init__.py", line 6, in <module>
    from owtf.utils.logger import OWTFLogger
  File "/development/cyber/owtf/owtf/utils/logger.py", line 10, in <module>
    from owtf.utils.file import catch_io_errors, get_log_path, FileOperations, get_logs_dir
  File "/development/cyber/owtf/owtf/utils/file.py", line 13, in <module>
    from owtf.settings import LOGS_DIR, OUTPUT_PATH, OWTF_CONF, TARGETS_DIR, WORKER_LOG_DIR
  File "/development/cyber/owtf/owtf/settings.py", line 15, in <module>
    import yaml
```

and with python3 (installed via brew):
```
Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    from setuptools import setup, find_packages
ModuleNotFoundError: No module named 'setuptools'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 8, in <module>
    from distutils.core import setup, find_packages
ImportError: cannot import name 'find_packages' from 'distutils.core' (/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/core.py)
```

## Expected Behavior
install script should run.

## Current Behavior
getting above errors.

## Possible Solution
?

## Context
Just trying to get OWTF running, I do have a Kali VM, but failing run on there as well.

## Your Environment
Python 2.7.10
pip 19.0.3 from /Library/Python/2.7/site-packages/pip-19.0.3-py2.7.egg/pip (python 2.7)

**Comment by johnbowdenatfacet** [comment]
I managed to get pip3 installed and dependencies for the setup script.  When I run owtf i get the following: 
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (tornado 6.0.1 (/usr/local/lib/python3.7/site-packages), Requirement.parse('tornado==5.0.2'), {'owtf'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/owtf", line 4, in <module>
    __import__('pkg_resources').require('owtf==2.4.0')
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3191, in <module>
    @_call_aside
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3175, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3204, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pycurl==7.43.0.2' distribution was not found and is required by owtf
```

**Comment by johnbowdenatfacet** [comment]
Getting somewhere, now i get the following from owtf:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/SQLAlchemy-1.1.13-py3.7-macosx-10.14-x86_64.egg/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/usr/local/lib/python3.7/site-packages/SQLAlchemy-1.1.13-py3.7-macosx-10.14-x86_64.egg/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
psycopg2.ProgrammingError: relation "plugins" does not exist
LINE 2: FROM plugins
```

**Comment by viyatb** [comment]
This should be fixed in https://github.com/owtf/owtf/commit/79d955694859036e194f90b6e0f594a84ae0114e. `git pull origin develop && python setup.py develop` should fix existing installations.
