### ISSUE TITLE
Typing on python3.7.2 error

### ISSUE THREAD

**Issue by diofeher** [owtf/owtf#1021]
Traceback (most recent call last):
  File "/Users/diofeher/.virtualenvs/owtf/bin/owtf", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/Users/diofeher/workspace/owtf/bin/owtf", line 7, in <module>
    from owtf.core import main
  File "/Users/diofeher/workspace/owtf/owtf/__init__.py", line 4, in <module>
    from typing import Any, NamedTuple
  File "/Users/diofeher/.virtualenvs/owtf/lib/python3.7/site-packages/typing-3.6.6-py3.7.egg/typing.py", line 1356, in <module>
    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
  File "/Users/diofeher/.virtualenvs/owtf/lib/python3.7/site-packages/typing-3.6.6-py3.7.egg/typing.py", line 1004, in __new__
    self._abc_registry = extra._abc_registry
AttributeError: type object 'Callable' has no attribute '_abc_registry'

OWTF run is failing with the following error. For what I searched, typing is in standard library since python3.5, so it gets conflicted.

## Expected Behavior
OWTF should run

## Current Behavior
To fix the error, you need to edit the file in your python library, in this case 
/Users/diofeher/.virtualenvs/owtf/lib/python3.7/site-packages/typing-3.6.6-py3.7.egg/typing.py

## Possible Solution
I would suggest adding typing==3.6.6;  python_version <3.5 but I'm not sure if this is going to work as this typing version is installed by sqlalchemy-mixes

## Steps to Reproduce (for bugs)

1. Try to run owtf on mac os x 10.12 using python 3.7.2

## Your Environment
* Installation method used:
* Version/branch used: master
* Operating System and version (like Kali, Debian, ArchLinux, etc): Mac OS X 10.12

**Comment by viyatb** [comment]
@diofeher thanks for the reporting this issue! Let me look at it tonight.

**Comment by blshkv** [comment]
https://github.com/owtf/owtf/issues/949
