### ISSUE TITLE
Foreign key associated with column 'command_register.plugin_key' could not find table 'plugins'

### ISSUE THREAD

**Issue by mehran-01** [owtf/owtf#1040]
I still can not run owtf on Kali, I tried both ways(running through docker and without it).
At last step when run owtf getting an error as below. Any idea?
## Expected Behavior
Run OWTF on Kali

## Current Behavior

sqlalchemy.exc.NoReferencedTableError: Foreign key associated with column 'command_register.plugin_key' could not find table 'plugins' with which to generate a foreign key to target column 'key

## Logs @ /var/log/postgresql/postgresql-11-main.log
[22824] owtf_db_user@owtf_db LOG:  could not receive data from client: Connection reset by peer

**Comment by CypherAlmasy** [comment]
I ran in to this as well.  I did a bisect and tracked the issue down to [this commit](https://github.com/owtf/owtf/commit/aa264dca55f4374dd372b8664fe62c75082179ca).  It looks like an unintended side effect from the added import in owtf/api/handlers/misc.py.  I can try to muddle through a PR later to fix it, though someone more familiar with the codebase than I am would probably be able to fix it more quickly.

The last release tag (v2.6.0) appears to work with Python 2, so you can clone the repo and run "git checkout v2.6.0" prior to running "python setup.py develop" to get it working.

**Comment by secureonelabs** [comment]
Same issue here as mehran-01. Any ETA on a fix?

**Comment by jumson** [comment]
Same issue, with Kali, using default branch, and then a new VM with ubuntu 19.04. Tried both the Docker and the Manual way of PostreSQL, same error:

```
osboxes@osboxes:~/owtf$ python -m owtf
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "owtf/owtf/__main__.py", line 8, in <module>
    from owtf.core import main
  File "owtf/owtf/core.py", line 18, in <module>
    from owtf.api.main import start_server
  File "owtf/api/main.py", line 15, in <module>
    from owtf.api.routes import API_v1_HANDLERS, UI_HANDLERS
  File "owtf/api/routes.py", line 11, in <module>
    from owtf.api.handlers.misc import ErrorDataHandler, DashboardPanelHandler, ProgressBarHandler
  File "owtf/api/handlers/misc.py", line 14, in <module>
    from owtf.managers.poutput import get_severity_freq, plugin_count_output
  File "owtf/managers/poutput.py", line 12, in <module>
    from owtf.managers.target import target_manager, target_required
  File "owtf/managers/target.py", line 25, in <module>
    from owtf.plugin.params import plugin_params
  File "owtf/plugin/params.py", line 375, in <module>
    plugin_params = PluginParams()
  File "owtf/plugin/params.py", line 34, in __init__
    self.session = get_scoped_session()
  File "owtf/db/session.py", line 60, in get_scoped_session
    Session.configure(bind=get_db_engine())
  File "owtf/db/session.py", line 52, in get_db_engine
    Model.metadata.create_all(engine)
  File "/home/osboxes/.local/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 3949, in create_all
    tables=tables)
  File "/home/osboxes/.local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1929, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/home/osboxes/.local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1538, in _run_visitor
    **kwargs).traverse_single(element)
  File "/home/osboxes/.local/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single
    return meth(obj, **kw)
  File "/home/osboxes/.local/lib/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 712, in visit_metadata
    [t for t in tables if self._can_create_table(t)])
  File "/home/osboxes/.local/lib/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 1063, in sort_tables_and_constraints
    dependent_on = fkc.referred_table
  File "/home/osboxes/.local/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 2961, in referred_table
    return self.elements[0].column.table
  File "/home/osboxes/.local/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 764, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/home/osboxes/.local/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 1858, in column
    tablekey)
sqlalchemy.exc.NoReferencedTableError: Foreign key associated with column 'command_register.plugin_key' could not find table 'plugins' with which to generate a foreign key to target column 'key'

```

**Comment by sonawanesarvesh** [comment]
Hi 
i tried both docker and git clone installation on Kali 2019.3 and Kali 2018.4 both version but i am always failing with same error -  (MainProcess.log is also empty)

sqlalchemy.exc.NoReferencedTableError: Foreign key associated with column 'command_register.plugin_key' could not find table 'plugins' with which to generate a foreign key to target column 'key'

**Comment by smogg** [comment]
Same problem here ✋

**Comment by jandress** [comment]
Same issue here. Is this project dead?

**Comment by NishealJ** [comment]
Hi @smogg, @jandress,

 For a temporary run please goto` owtf/models/command.py` and replace  `plugin_key = Column(String, ForeignKey("plugins.key"))` this with   `plugin_key = Column(String)`

Also, take a look at the same in this PR #1045 

Let me know if that works!
