### ISSUE TITLE
Outputs to plugins not being displayed

### ISSUE THREAD

**Issue by Ashrith-Shetty** [owtf/owtf#1062]
The output on running the plugin is not being displayed.
Eg:- On trying to access output of browser fingerprinting on this endpoint` /api/v1/targets/4/poutput/?plugin_code=OWTF-IG-004` Internal Server Error is being Displayed.

## Expected Behavior

On running the plugins, the output for the target needs to be displayed.

## Steps to Reproduce (for bugs)

1. RUN OWTF
2. Select Plugin.
![Screenshot from 2020-04-27 01-29-54](https://user-images.githubusercontent.com/52630129/80318276-b1b84600-8826-11ea-952c-c4b55be61611.png)
`Uncaught exception GET /api/v1/targets/4/poutput/?plugin_code=OWTF-IG-004 (127.0.0.1)
HTTPServerRequest(protocol='http', host='localhost:8009', method='GET', uri='/api/v1/targets/4/poutput/?plugin_code=OWTF-IG-004', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/home/anonymous/Desktop/vdevelop/owtf/vdevelop/lib/python3.6/site-packages/SQLAlchemy-1.1.13-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/home/anonymous/Desktop/vdevelop/owtf/vdevelop/lib/python3.6/site-packages/SQLAlchemy-1.1.13-py3.6-linux-x86_64.egg/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
psycopg2.ProgrammingError: operator does not exist: character varying = bytea
LINE 3: ...puts.target_id = 4 AND plugin_outputs.plugin_code IN ('\x4f5...
                                                             ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/anonymous/Desktop/vdevelop/owtf/vdevelop/lib/python3.6/site-packages/tornado/web.py", line 1541, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/home/anonymous/Desktop/vdevelop/owtf/owtf/api/handlers/plugin.py", line 276, in get
    results = get_all_poutputs(self.session, filter_data, target_id=int(target_id), inc_output=True)
  File "/home/anonymous/Desktop/vdevelop/owtf/owtf/managers/target.py", line 75, in wrapped_function
    return func(*args, **kwargs)
  File "/home/anonymous/Desktop/vdevelop/owtf/owtf/managers/poutput.py", line 145, in get_all_poutputs
    results = poutput_gen_query(session, filter_data, target_id).all()
  File "/home/anonymous/Desktop/vdevelop/owtf/vdevelop/lib/python3.6/site-packages/SQLAlchemy-1.1.13-py3.6-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2703, in all
    return list(self)
  File "/home/anonymous/Desktop/vdevelop/owtf/vdevelop/lib/python3.6/site-packages/SQLAlchemy-1.1.13-py3.6-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2855, in __iter__
    return self._execute_and_instances(context)
  File "/home/anonymous/Desktop/vdevelop/owtf/vdevelop/lib/python3.6/site-packages/SQLAlchemy-1.1.13-py3.6-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2878, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/anonymous/Desktop/vdevelop/owtf/vdevelop/lib/python3.6/site-packages/SQLAlchemy-1.1.13-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/home/anonymous/Desktop/vdevelop/owtf/vdevelop/lib/python3.6/site-packages/SQLAlchemy-1.1.13-py3.6-linux-x86_64.egg/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/anonymous/Desktop/vdevelop/owtf/vdevelop/lib/python3.6/site-packages/SQLAlchemy-1.1.13-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/anonymous/Desktop/vdevelop/owtf/vdevelop/lib/python3.6/site-packages/SQLAlchemy-1.1.13-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/home/anonymous/Desktop/vdevelop/owtf/vdevelop/lib/python3.6/site-packages/SQLAlchemy-1.1.13-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/home/anonymous/Desktop/vdevelop/owtf/vdevelop/lib/python3.6/site-packages/SQLAlchemy-1.1.13-py3.6-linux-x86_64.egg/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/anonymous/Desktop/vdevelop/owtf/vdevelop/lib/python3.6/site-packages/SQLAlchemy-1.1.13-py3.6-linux-x86_64.egg/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/home/anonymous/Desktop/vdevelop/owtf/vdevelop/lib/python3.6/site-packages/SQLAlchemy-1.1.13-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/home/anonymous/Desktop/vdevelop/owtf/vdevelop/lib/python3.6/site-packages/SQLAlchemy-1.1.13-py3.6-linux-x86_64.egg/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) operator does not exist: character varying = bytea
LINE 3: ...puts.target_id = 4 AND plugin_outputs.plugin_code IN ('\x4f5...
                                                             ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
 [SQL: 'SELECT plugin_outputs.target_id AS plugin_outputs_target_id, plugin_outputs.plugin_key AS plugin_outputs_plugin_key, plugin_outputs.id AS plugin_outputs_id, plugin_outputs.plugin_code AS plugin_outputs_plugin_code, plugin_outputs.plugin_group AS plugin_outputs_plugin_group, plugin_outputs.plugin_type AS plugin_outputs_plugin_type, plugin_outputs.date_time AS plugin_outputs_date_time, plugin_outputs.start_time AS plugin_outputs_start_time, plugin_outputs.end_time AS plugin_outputs_end_time, plugin_outputs.output AS plugin_outputs_output, plugin_outputs.error AS plugin_outputs_error, plugin_outputs.status AS plugin_outputs_status, plugin_outputs.user_notes AS plugin_outputs_user_notes, plugin_outputs.user_rank AS plugin_outputs_user_rank, plugin_outputs.owtf_rank AS plugin_outputs_owtf_rank, plugin_outputs.output_path AS plugin_outputs_output_path \nFROM plugin_outputs \nWHERE plugin_outputs.target_id = %(target_id_1)s AND plugin_outputs.plugin_code IN (%(plugin_code_1)s) ORDER BY plugin_outputs.plugin_key ASC'] [parameters: {'target_id_1': 4, 'plugin_code_1': <psycopg2.extensions.Binary object at 0x7f9ccbddfeb8>}]`

**Comment by viyatb** [comment]
Closing this as stale. There has not been a current repro in a long time, and the code has moved enough that the original report is no longer actionable. If it still happens on current `develop`, a fresh issue with steps and logs would be more useful.
