### ISSUE TITLE
Running with Docker compose: No such file or directory: '/root/.owtf/build/index.html'

### ISSUE THREAD

**Issue by sebix** [owtf/owtf#1203]
## Expected Behavior
http://0.0.0.0:8009/ presents an interface

## Current Behavior
```
Traceback (most recent call last):
  File "/bin/owtf/lib/python3.9/site-packages/tornado/web.py", line 1590, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/bin/owtf/lib/python3.9/site-packages/owtf-2.6.0-py3.9.egg/owtf/api/handlers/index.py", line 35, in get
    self.render("index.html")
  File "/bin/owtf/lib/python3.9/site-packages/tornado/web.py", line 766, in render
    html = self.render_string(template_name, **kwargs)
  File "/bin/owtf/lib/python3.9/site-packages/tornado/web.py", line 904, in render_string
    t = loader.load(template_name)
  File "/bin/owtf/lib/python3.9/site-packages/tornado/template.py", line 425, in load
    self.templates[name] = self._create_template(name)
  File "/bin/owtf/lib/python3.9/site-packages/tornado/template.py", line 452, in _create_template
    with open(path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/root/.owtf/build/index.html'
```
## Steps to Reproduce (for bugs)
Follow https://github.com/owtf/owtf#running-as-a-docker-container
1. git clone https://github.com/owtf/owtf
2. cd owtf
3. make compose

## Logs
`/tmp/owtf/ui_server.log` has just the same error message as above

## Context
Trying to run the application.

## Your Environment
* Installation method used: Docker compose
* Version/branch used: develop and v.2.6.0
* Operating System and version (like Kali, Debian, ArchLinux, etc): openSUSE Tumbleweed
* pip/setuptools version: pip 22.2.2
* sudo access: docker container uses root

Some more information not fitting in the above sections:
`/root/.owtf/build/` does not exist at all. Various other issues reporting the same issue exist, proposing to run yarn manually, but that does not bring the files into `/root/.owtf/build/` inside the container? Also I have noticed that the Dockerfile does not call yarn anywhere.

**Comment by Pratham1812** [comment]
Hey try downloading and using `docker-compose`, I had similar issue when I used `docker compose`

**Comment by viyatb** [comment]
Closing this as stale. The install/Docker setup has changed a lot since this was opened, so this report is no longer actionable as-is. If this still reproduces on current `develop`, please open a fresh issue with OS, Docker/Python versions, and the current logs.
