### ISSUE TITLE
INSTALLATION FAILED 2023

### ISSUE THREAD

**Issue by dookofcrds** [owtf/owtf#1235]
Running Parrot OS fully up to date i5 8gb of ram ran install in root account and normal user both FAILED 
tried installing as docker and standalone version both failed 

┌─[root@parrot]─[~/Desktop]
└──╼ #git clone https://github.com/owtf/owtf
Cloning into 'owtf'...
remote: Enumerating objects: 24860, done.
remote: Counting objects: 100% (1147/1147), done.
remote: Compressing objects: 100% (767/767), done.
remote: Total 24860 (delta 605), reused 790 (delta 345), pack-reused 23713
Receiving objects: 100% (24860/24860), 26.38 MiB | 10.96 MiB/s, done.
Resolving deltas: 100% (15445/15445), done.
┌─[root@parrot]─[~/Desktop]
└──╼ #cd owtf
┌─[root@parrot]─[~/Desktop/owtf]
└──╼ #make compose
--> Running the Docker Compose setup
docker-compose -f docker/docker-compose.dev.yml up
/usr/lib/python3/dist-packages/paramiko/transport.py:219: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
Starting docker_db_1 ... done
Recreating docker_owtf_1 ... done
Attaching to docker_db_1, docker_owtf_1
db_1    | 
db_1    | PostgreSQL Database directory appears to contain a database; Skipping initialization
db_1    | 
db_1    | 2023-08-07 00:32:27.014 UTC [1] LOG:  starting PostgreSQL 15.3 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r10) 12.2.1 20220924, 64-bit
db_1    | 2023-08-07 00:32:27.014 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1    | 2023-08-07 00:32:27.014 UTC [1] LOG:  listening on IPv6 address "::", port 5432
owtf_1  | wait-for-it.sh: waiting 15 seconds for db:5432
owtf_1  | wait-for-it.sh: db:5432 is available after 0 seconds
owtf_1  | 
owtf_1  |          _____ _ _ _ _____ _____
owtf_1  |         |     | | | |_   _|   __|
owtf_1  |         |  |  | | | | | | |   __|
owtf_1  |         |_____|_____| |_| |__|
owtf_1  | 
owtf_1  |             @owtfp
owtf_1  |         http://owtf.org
owtf_1  |         Version: 2.6.0
owtf_1  |         
db_1    | 2023-08-07 00:32:27.342 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
owtf_1  | [+] Loading /root/.owtf/conf/framework.yaml..
owtf_1  | /bin/owtf/lib/python3.9/site-packages/owtf-2.6.0-py3.9.egg/owtf/managers/config.py:35: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
owtf_1  |   config_map = yaml.load(FileOperations.open(file_path, "r"))
owtf_1  | [+] Loading /root/.owtf/conf/general.yaml..
owtf_1  | [+] Loading resources from: /root/.owtf/conf/resources.cfg..
db_1    | 2023-08-07 00:32:27.627 UTC [24] LOG:  database system was shut down at 2023-08-07 00:21:49 UTC
db_1    | 2023-08-07 00:32:27.726 UTC [1] LOG:  database system is ready to accept connections
owtf_1  | Traceback (most recent call last):
owtf_1  |   File "/bin/owtf/bin/owtf", line 33, in <module>
owtf_1  |     sys.exit(load_entry_point('owtf==2.6.0', 'console_scripts', 'owtf')())
owtf_1  |   File "/bin/owtf/lib/python3.9/site-packages/owtf-2.6.0-py3.9.egg/owtf/core.py", line 330, in main
db_1    | 2023-08-07 00:32:31.175 UTC [28] LOG:  incomplete startup packet
owtf_1  |     load_resources_from_file(
owtf_1  |   File "/bin/owtf/lib/python3.9/site-packages/owtf-2.6.0-py3.9.egg/owtf/managers/resource.py", line 136, in load_resources_from_file
owtf_1  |     resources = get_resources_from_file(file_path)
owtf_1  |   File "/bin/owtf/lib/python3.9/site-packages/owtf-2.6.0-py3.9.egg/owtf/managers/resource.py", line 108, in get_resources_from_file
owtf_1  |     if "#" == line[0]:
owtf_1  | IndexError: string index out of range
^CGracefully stopping... (press Ctrl+C again to force)
Stopping docker_owtf_1   ... done
Stopping docker_db_1     ... done

┌─[✗]─[root@parrot]─[~/Desktop/owtf]
└──╼ #python3 setup.py develop
running develop
running egg_info
creating owtf.egg-info
writing owtf.egg-info/PKG-INFO
writing dependency_links to owtf.egg-info/dependency_links.txt
writing entry points to owtf.egg-info/entry_points.txt
writing requirements to owtf.egg-info/requires.txt
writing top-level names to owtf.egg-info/top_level.txt
writing manifest file 'owtf.egg-info/SOURCES.txt'
reading manifest file 'owtf.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*' under directory 'owtf/webui'
warning: no previously-included files found matching ''node_modules''
warning: no previously-included files found matching ''node_modules.*''
adding license file 'LICENSE.md'
adding license file 'AUTHORS.md'
writing manifest file 'owtf.egg-info/SOURCES.txt'
running build_ext
Creating /usr/local/lib/python3.9/dist-packages/owtf.egg-link (link to .)
Adding owtf 2.6.0 to easy-install.pth file
Installing owtf script to /usr/local/bin
Installing owtf script to /usr/local/bin

Installed /root/Desktop/owtf
Processing dependencies for owtf==2.6.0
Searching for sqlalchemy_mixins==1.1
Reading https://pypi.org/simple/sqlalchemy_mixins/
No local packages or working download links found for sqlalchemy_mixins==1.1
error: Could not find suitable distribution for Requirement.parse('sqlalchemy_mixins==1.1')

**Comment by dookofcrds** [comment]
┌─[✗]─[root@parrot]─[/usr/bin]
└──╼ #owtf

         _____ _ _ _ _____ _____
        |     | | | |_   _|   __|
        |  |  | | | | | | |   __|
        |_____|_____| |_| |__|

            @owtfp
        http://owtf.org
        Version: 2.6.0
        
[+] Loading /root/.owtf/conf/framework.yaml..
/home/dook/Desktop/owtf/owtf/managers/config.py:35: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config_map = yaml.load(FileOperations.open(file_path, "r"))
[+] Loading /root/.owtf/conf/general.yaml..
[+] Loading resources from: /root/.owtf/conf/resources.cfg..
Traceback (most recent call last):
  File "/usr/local/bin/owtf", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/dook/Desktop/owtf/bin/owtf", line 11, in <module>
    main()
  File "/home/dook/Desktop/owtf/owtf/core.py", line 330, in main
    load_resources_from_file(
  File "/home/dook/Desktop/owtf/owtf/managers/resource.py", line 136, in load_resources_from_file
    resources = get_resources_from_file(file_path)
  File "/home/dook/Desktop/owtf/owtf/managers/resource.py", line 108, in get_resources_from_file
    if "#" == line[0]:
IndexError: string index out of range

**Comment by dookofcrds** [comment]
> ┌─[✗]─[root@parrot]─[/usr/bin] └──╼ #owtf
> 
> ```
>      _____ _ _ _ _____ _____
>     |     | | | |_   _|   __|
>     |  |  | | | | | | |   __|
>     |_____|_____| |_| |__|
> 
>         @owtfp
>     http://owtf.org
>     Version: 2.6.0
> ```
> 
> [+] Loading /root/.owtf/conf/framework.yaml.. /home/dook/Desktop/owtf/owtf/managers/config.py:35: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details. config_map = yaml.load(FileOperations.open(file_path, "r")) [+] Loading /root/.owtf/conf/general.yaml.. [+] Loading resources from: /root/.owtf/conf/resources.cfg.. Traceback (most recent call last): File "/usr/local/bin/owtf", line 7, in exec(compile(f.read(), **file**, 'exec')) File "/home/dook/Desktop/owtf/bin/owtf", line 11, in main() File "/home/dook/Desktop/owtf/owtf/core.py", line 330, in main load_resources_from_file( File "/home/dook/Desktop/owtf/owtf/managers/resource.py", line 136, in load_resources_from_file resources = get_resources_from_file(file_path) File "/home/dook/Desktop/owtf/owtf/managers/resource.py", line 108, in get_resources_from_file if "#" == line[0]: IndexError: string index out of range

new issue, maybe im dumb and cant follow basic steps but lmk if yall can help

**Comment by viyatb** [comment]
Closing this as stale. The install/Docker setup has changed a lot since this was opened, so this report is no longer actionable as-is. If this still reproduces on current `develop`, please open a fresh issue with OS, Docker/Python versions, and the current logs.
