### ISSUE TITLE
Pressing ^C when a plugin is running freezes OWTF 

### ISSUE THREAD

**Issue by DePierre** [owtf/owtf#354]
When working on the patch that forces OWTF to rank aborted plugins as well, I realized that pressing _^C_ in the console when a plugin is running makes OWTF to freeze.

I can't find any useful information in the logs (not in ui_server.log, not in file_server.log, nor anywhere) but when pressing a second time _^C_ in the console, I have the following traceback:

``` py3tb
[-] __________ 1 - Target: http://127.0.0.1:9000 -> Plugin: Skipfish Unauthenticated (active) __________
[-] 
[-] Executing :

cd owtf_review/targets/http__127.0.0.19000/partial/Skipfish_Unauthenticated/active; touch new_dict.wl ; cd /usr/share/skipfish/ ; /usr/bin/skipfish -t 90 -i 90 -w 90 -f1000 -b f -u -o /home/depierre/git-repo/owcs/owtf/owtf_review/targets/http__127.0.0.19000/partial/Skipfish_Unauthenticated/active/skipfish_report -S /usr/share/skipfish//dictionaries/minimal.wl -W /home/depierre/git-repo/owcs/owtf/owtf_review/targets/http__127.0.0.19000/partial/Skipfish_Unauthenticated/active/new_dict.wl http://127.0.0.1:9000


[-] 
[-] ------> Execution Start Date/Time: 26/10/2014-12:09
[-] 
^CNone
skipfish web application scanner - version 2.10b
[*] Scan in progress, please stay tuned...

[!] Scan aborted by user, bailing out!
[+] Wordlist '/home/depierre/git-repo/owcs/owtf/owtf_review/targets/http__127.0.0.19000/partial/Skipfish_Unauthenticated/active/new_dict.wl' updated (4 new words added).
[+] Copying static resources...
[+] Sorting and annotating crawl nodes: 5
[+] Looking for duplicate entries: 5
[+] Counting unique nodes: 5
[+] Saving pivot data for third-party tools...
[+] Writing scan description...
[+] Writing crawl tree: 5
[+] Generating summary views...
[+] Report saved to '/home/depierre/git-repo/owcs/owtf/owtf_review/targets/http__127.0.0.19000/partial/Skipfish_Unauthenticated/active/skipfish_report/index.html' [0xd687afd6].
[+] This was a great day for science!


[-] 
The Command was aborted by the user: Please check the report and plugin output files
[-] Time=2s, 435ms
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib/python2.7/multiprocessing/util.py", line 325, in _exit_function
    p.join()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 145, in join
    res = self._popen.wait(timeout)
  File "/usr/lib/python2.7/multiprocessing/forking.py", line 154, in wait
    return self.poll(0)
  File "/usr/lib/python2.7/multiprocessing/forking.py", line 135, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib/python2.7/multiprocessing/util.py", line 325, in _exit_function
    p.join()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 145, in join
    res = self._popen.wait(timeout)
  File "/usr/lib/python2.7/multiprocessing/forking.py", line 154, in wait
    return self.poll(0)
  File "/usr/lib/python2.7/multiprocessing/forking.py", line 135, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
```

I first thought that I made an error in my patch but it also occurs in the previous commit 75c478a.

**Comment by rishi62** [comment]
How to stop the inbound proxy?

**Comment by DePierre** [comment]
@rishi62 This is a known issue and it's been around for a while and I lost hope that it would disappear. It gave me quite a lot to work around when I wrote the OWTF testing framework.

In some cases, when cancelling a plugin (using ^C like in your case), OWTF will not properly release all its resources (postgresql, proxy, etc.) and they will become zombie processes.

The zombie processes will timeout after a couple of minutes and you will be able to start OWTF again.

**Comment by rishi62** [comment]
I have to restart my system to start owtf again i guess those zombie processes are not terminating.

**Comment by DePierre** [comment]
@rishi62 You could have done otherwise. There was no need to restart. For instance, you could check the zombies using `ps` or find the proxy process by looking at the output of `netstat`

**Comment by viyatb** [comment]
Fixed in develop.
