### ISSUE TITLE
OWTF-DV-004 semi passive no output

### ISSUE THREAD

**Issue by marioskourtesis** [owtf/owtf#404]
Execurting the semi_passive/OWTF-DV-004 plug-in returns no output and logs the following error in the /tmp/owtf/ui_server.log

[E 150404 21:09:47 web:1407] Uncaught exception POST /api/worklist/ (127.0.0.1)
    HTTPServerRequest(protocol='http', host='127.0.0.1:8009', method='POST', uri='/api/worklist/', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Content-Length': '70', 'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Host': '127.0.0.1:8009', 'Accept': '*/*', 'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:31.0) Gecko/20100101 Firefox/31.0 Iceweasel/31.6.0', 'Connection': 'keep-alive', 'X-Requested-With': 'XMLHttpRequest', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache', 'Referer': 'http://127.0.0.1:8009/ui/targets/5', 'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'})
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/tornado/web.py", line 1332, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/root/owtf/framework/interface/api_handlers.py", line 608, in post
        self.get_argument("force_overwrite", "False"))
      File "/root/owtf/framework/db/worklist_manager.py", line 165, in add_work
        "plugin_key": plugin["key"]
      File "/root/owtf/framework/db/target_manager.py", line 57, in wrapped_function
        return func(*args, **kwargs)
      File "/root/owtf/framework/db/poutput_manager.py", line 177, in DeleteAll
        results = query.delete()
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2670, in delete
        delete_op.exec_()
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 896, in exec_
        self._do_pre_synchronize()
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 958, in _do_pre_synchronize
        eval_condition(obj)]
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/evaluator.py", line 90, in evaluate
        value = sub_evaluate(obj)
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/evaluator.py", line 115, in evaluate
        left_val = eval_left(obj)
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/evaluator.py", line 72, in <lambda>
        return lambda obj: get_corresponding_attr(obj)
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 239, in __get__
        return self.impl.get(instance_state(instance), dict_)
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 589, in get
        value = callable_(state, passive)
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/state.py", line 424, in __call__
        self.manager.deferred_scalar_loader(self, toload)
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/loading.py", line 614, in load_scalar_attributes
        raise orm_exc.ObjectDeletedError(state)
    ObjectDeletedError: Instance '<PluginOutput at 0x42fe550>' has been deleted, or its row is otherwise not present.
[E 150404 21:09:47 web:1811] 500 POST /api/worklist/ (127.0.0.1) 34.73ms
[E 150404 21:09:49 web:1407] Uncaught exception POST /api/worklist/ (127.0.0.1)
    HTTPServerRequest(protocol='http', host='127.0.0.1:8009', method='POST', uri='/api/worklist/', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Content-Length': '70', 'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Host': '127.0.0.1:8009', 'Accept': '*/*', 'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:31.0) Gecko/20100101 Firefox/31.0 Iceweasel/31.6.0', 'Connection': 'keep-alive', 'X-Requested-With': 'XMLHttpRequest', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache', 'Referer': 'http://127.0.0.1:8009/ui/targets/5', 'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'})
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/tornado/web.py", line 1332, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/root/owtf/framework/interface/api_handlers.py", line 608, in post
        self.get_argument("force_overwrite", "False"))
      File "/root/owtf/framework/db/worklist_manager.py", line 165, in add_work
        "plugin_key": plugin["key"]
      File "/root/owtf/framework/db/target_manager.py", line 57, in wrapped_function
        return func(*args, **kwargs)
      File "/root/owtf/framework/db/poutput_manager.py", line 177, in DeleteAll
        results = query.delete()
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2670, in delete
        delete_op.exec_()
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 896, in exec_
        self._do_pre_synchronize()
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 958, in _do_pre_synchronize
        eval_condition(obj)]
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/evaluator.py", line 90, in evaluate
        value = sub_evaluate(obj)
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/evaluator.py", line 115, in evaluate
        left_val = eval_left(obj)
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/evaluator.py", line 72, in <lambda>
        return lambda obj: get_corresponding_attr(obj)
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 239, in __get__
        return self.impl.get(instance_state(instance), dict_)
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 589, in get
        value = callable_(state, passive)
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/state.py", line 424, in __call__
        self.manager.deferred_scalar_loader(self, toload)
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/loading.py", line 614, in load_scalar_attributes
        raise orm_exc.ObjectDeletedError(state)
    ObjectDeletedError: Instance '<PluginOutput at 0x42fe550>' has been deleted, or its row is otherwise not present.
[E 150404 21:09:49 web:1811] 500 POST /api/worklist/ (127.0.0.1) 26.62ms

**Comment by tunnelshade** [comment]
The traceback is different from the title of this bug. The empty output is because the call to `Requester.GetTransactions` in this plugin is not happening. Might be a problem of service locator.

**Comment by DePierre** [comment]
@marioskourtesis Hi, I am trying to reproduce the bug but I never have that 500 error in the logs. Would you have the steps/details in order to reach that bug?

**Comment by marioskourtesis** [comment]
@Tao, Hi
Try to run the "OWTF-IG-001 Spiders, Robots, and Crawlers robots.txt
Analysis" semipassive plugin.

**Comment by DePierre** [comment]
But isn't ``OWTF-DV-004`` the plugin ``Testing for Cross site flashing``? Anyway, I ran ``OWTF-IG-001`` as well and did not have any error.

I will try to run all semi-passive plugins against <https://www.owasp.org/index.php/OWASP_Vulnerable_Web_Applications_Directory_Project> like @7a suggested and see what I can find.

**Comment by delta24** [comment]
I ran the test @DePierre suggested above and there were no errors. Closing because I cannot reproduce it.
