### ISSUE TITLE
bootstrap.sh Fails while Installing in Kali

### ISSUE THREAD

**Issue by mushinnomushin** [owtf/owtf#416]
Installing collected packages: setuptools, certifi, EasyProcess, cryptography
  Found existing installation: setuptools 11.3.1
    Uninstalling setuptools-11.3.1:
      Successfully uninstalled setuptools-11.3.1
  Rolling back uninstall of setuptools
  Exception:
  Traceback (most recent call last):
    File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 232, in main
      status = self.run(options, args)
    File "/usr/local/lib/python2.7/dist-packages/pip/commands/install.py", line 347, in run
      root=options.root_path,
    File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 549, in install
      **kwargs
    File "/usr/local/lib/python2.7/dist-packages/pip/req/req_install.py", line 751, in install
      self.move_wheel_files(self.source_dir, root=root)
    File "/usr/local/lib/python2.7/dist-packages/pip/req/req_install.py", line 960, in move_wheel_files
      isolated=self.isolated,
    File "/usr/local/lib/python2.7/dist-packages/pip/wheel.py", line 137, in move_wheel_files
      name, user=user, home=home, root=root, isolated=isolated
    File "/usr/local/lib/python2.7/dist-packages/pip/locations.py", line 229, in distutils_scheme
      i = d.get_command_obj('install', create=True)
    File "/usr/lib/python2.7/distutils/dist.py", line 845, in get_command_obj
      klass = self.get_command_class(command)
    File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 428, in get_command_class
      self.cmdclass[command] = cmdclass = ep.load()
    File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2310, in load
      return self.resolve()
    File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2316, in resolve
      module = __import__(self.module_name, fromlist=['__name__'], level=0)
  ImportError: No module named command.install

**Comment by delta24** [comment]
The new Kali update messed up `pip` and `setuptools`. Temporary solutions:

####Option 1:
First run `pip install -U setuptools`,
Then run the command to upgrade your package (e.g. `pip install --upgrade lxml`)

####Option 2:
Upgrade pip using `get-pip`
Then run the command to upgrade the package (e.g. pip install --upgrade lxml)
To fix the problem once it's occurred (the error in question), you'll need to manually install the new `setuptools`, then **rerun install script (OWTF)**

Download `ez_setup.py` (https://bitbucket.org/pypa/setuptools/downloads/ez_setup.py)
Run `python ez_setup.py`
Then rerun your upgrade (ie, OWTF install script)

**Comment by mushinnomushin** [comment]
Running `pip install -u setuptools` allowed a new install to complete successfully. 

I'll try it on an install I'm upgrading later.

**Comment by mushinnomushin** [comment]
The fix works perfectly on the upgrade allowing it to finish installing. 

Thanks!

**Comment by 7a** [comment]
Should / can our installer be smart enough to do this automatically?

**Comment by delta24** [comment]
Maybe, but then every time Kali breaks `pip` or `setuptools`, our list of fixes will go on increasing -> this will increase/complicate the install process IMHO.

**Comment by mushinnomushin** [comment]
I agree. There's really no reason to try to fix all the things that get broken when Kali updates... although you may have jerks like me asking you questions.
