### ISSUE TITLE
Smarter Runner 

### ISSUE THREAD

**Issue by delta24** [owtf/owtf#430]
@7a : The runner should be smart enough to see if OWTF has been installed or not, to avoid stack traces like the following (on an **up-to-date Kali**):

```bash
# ./owtf.py 
Traceback (most recent call last):
  File "./owtf.py", line 42, in <module>
    verify_dependencies(os.path.dirname(os.path.abspath(sys.argv[0])) or '.')
  File "/root/owtf_develop/framework/dependency_check.py", line 58, in verify_dependencies
    owtf_reqs = pip.req.parse_requirements(
AttributeError: 'module' object has no attribute 'req'
```

### FIX :
`pip install pip --upgrade`  # this updates pip and replaces pip by pip2 
`apt-get install libpq-dev` # this fixes the error which occurs during installation of psycopg2

**Comment by delta24** [comment]
Closing as this was an old pip error. :)
