### ISSUE TITLE
Error in handling special characters in url

### ISSUE THREAD

**Issue by DoomTaper** [owtf/owtf#496]
If we write any special character in the url (lets say # ) "add target" button doen't work even after I refresh it.

![screenshot from 2015-08-07 19 35 52](https://cloud.githubusercontent.com/assets/10975138/9142537/4dec1e98-3d0e-11e5-926c-11bf6dd818f7.png)

![screenshot from 2015-08-07 19 36 07](https://cloud.githubusercontent.com/assets/10975138/9142547/63f48446-3d0e-11e5-93ce-34457dfc7909.png)

**Comment by DePierre** [comment]
@DoomTaper Hi there. I tried to add the target 'http://example#.com' and the 'Add Targets' button is working fine. It still works after trying to add the target, when refreshing the page, when switching back and forth between tabs.

Have you install the develop branch? Could you let us know what commit you are at? You can find the hash by ``cd``ing into ~/owtf and execute ``git log -1``.

**Comment by DoomTaper** [comment]
I was not on develop branch. After installing devlop branch as i run ./owtf.py I got the error stated below



Traceback (most recent call last):
  File "./owtf.py", line 300, in <module>
    main(sys.argv)
  File "./owtf.py", line 263, in main
    ComponentInitialiser.initialisation_phase_1(root_dir, owtf_pid)
  File "/root/Desktop/owtf_develop/owtf/framework/dependency_management/component_initialiser.py", line 69, in initialisation_phase_1
    PluginDB()
  File "/root/Desktop/owtf_develop/owtf/framework/db/plugin_manager.py", line 24, in __init__
    self.LoadWebTestGroups(self.config.FrameworkConfigGet("WEB_TEST_GROUPS"))
  File "/root/Desktop/owtf_develop/owtf/framework/db/plugin_manager.py", line 56, in LoadWebTestGroups
    group="web")
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1613, in merge
    load=load, _recursive=_recursive)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1652, in _merge
    merged = self.query(mapper.class_).get(key[1])
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 820, in get
    return loading.load_on_ident(self, key)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/loading.py", line 231, in load_on_ident
    return q.one()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2369, in one
    ret = list(self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2412, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2427, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 729, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 321, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 826, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 958, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1160, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 951, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 436, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (ProgrammingError) column test_groups.priority does not exist
LINE 1: ..._groups_hint, test_groups.url AS test_groups_url, test_group...
                                                             ^
 'SELECT test_groups.code AS test_groups_code, test_groups."group" AS test_groups_group, test_groups.descrip AS test_groups_descrip, test_groups.hint AS test_groups_hint, test_groups.url AS test_groups_url, test_groups.priority AS test_groups_priority \nFROM test_groups \nWHERE test_groups.code = %(param_1)s' {'param_1': 'OWTF-IG-001'}

**Comment by tunnelshade** [comment]
Clean up your db schema. Use scripts/db_setup.sh

**Comment by DoomTaper** [comment]
Ya it is working now!! but can you brief me about the error

**Comment by delta24** [comment]
Closing as duplicate issue is closed...
