### ISSUE TITLE
owtf install on Kali2 fails - cryptography

### ISSUE THREAD

**Issue by macubergeek** [owtf/owtf#509]
Ran the installer script on kale and install failed:

  Found existing installation: cryptography 0.9.3
    Not uninstalling cryptography at /usr/lib/python2.7/dist-packages, owned by OS
  Running setup.py install for cryptography
    
    Installed /tmp/pip-build-UP8H5r/cryptography/cffi-1.2.1-py2.7-linux-x86_64.egg
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-UP8H5r/cryptography/setup.py", line 307, in <module>
        **keywords_with_side_effects(sys.argv)
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 266, in __init__
        _Distribution.__init__(self,attrs)
      File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 301, in finalize_options
        ep.load()(self, ep.name, value)
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
        ['__name__'])
    ImportError: No module named setuptools_ext
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-UP8H5r/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-VjSJ28-record/install-record.txt --single-version-externally-managed --compile:
    

Installed /tmp/pip-build-UP8H5r/cryptography/cffi-1.2.1-py2.7-linux-x86_64.egg

Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/tmp/pip-build-UP8H5r/cryptography/setup.py", line 307, in <module>

    **keywords_with_side_effects(sys.argv)

  File "/usr/lib/python2.7/distutils/core.py", line 111, in setup

    _setup_distribution = dist = klass(attrs)

  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 266, in __init__

    _Distribution.__init__(self,attrs)

**Comment by delta24** [comment]
Are you using a pre-built VMware image for Kali 2.0? There have been some `setuptools` problems reported for it.

**Comment by macubergeek** [comment]
No I built the VMware image myself from iso

**Comment by delta24** [comment]
Can you give the `setuptools` version from your VM? `pip show setuptools`

**Comment by macubergeek** [comment]
ok here it is:

root@kali2:~/Desktop# pip show setuptools
---
Name: setuptools
Version: 18.2
Location: /usr/local/lib/python2.7/dist-packages
Requires: 
root@kali2:~/Desktop#

**Comment by delta24** [comment]
Can you check this fix https://github.com/byt3bl33d3r/MITMf/issues/159?

**Comment by macubergeek** [comment]
Didn't work
I tried that last night. There is no requirements.txt file in the version of owtf I pulled down with git.

**Comment by macubergeek** [comment]
there is an install/owtf.pip file which lists the dependencies but cryptography isn't in there. btw python-cryptography is already installed in Kali2

**Comment by delta24** [comment]
Yes, no requirements.txt file. But I meant this:
`pip uninstall cryptography`
`apt-get install python-cryptography`

**Comment by macubergeek** [comment]
pip uninstall doesn't work:

> sudo pip uninstall cryptography
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 9, in <module>
    load_entry_point('pip==7.1.1', 'console_scripts', 'pip')()
  File "/Library/Python/2.7/site-packages/pip-7.1.1-py2.7.egg/pip/__init__.py", line 217, in main
    return command.main(cmd_args)
  File "/Library/Python/2.7/site-packages/pip-7.1.1-py2.7.egg/pip/basecommand.py", line 182, in main
    for name in ["pip._vendor", "distlib", "requests", "urllib3"]
  File "/Library/Python/2.7/site-packages/pip-7.1.1-py2.7.egg/pip/compat/dictconfig.py", line 565, in dictConfig
    dictConfigClass(config).configure()
  File "/Library/Python/2.7/site-packages/pip-7.1.1-py2.7.egg/pip/compat/dictconfig.py", line 332, in configure
    del logging._handlerList[:]
AttributeError: 'module' object has no attribute '_handlerList'

**Comment by macubergeek** [comment]
pip uninstall cryptography doesn't work on Kali2
root@kali2:~# pip uninstall cryptography
Not uninstalling cryptography at /usr/lib/python2.7/dist-packages, owned by OS

**Comment by macubergeek** [comment]
don't know if this helps but:
root@kali2:/opt/gitlist# pip freeze | grep crypto
cryptography==0.9.3
pycrypto==2.6.1
pycryptopp==0.6.0.1206569328141510525648634803928199668821045408958

**Comment by macubergeek** [comment]
don't know if this helps but:
root@kali2:/opt/gitlist# pip freeze | grep crypto
cryptography==0.9.3
pycrypto==2.6.1
pycryptopp==0.6.0.1206569328141510525648634803928199668821045408958

So the python cryptography module is already installed so when I go to install owtf it craps out because it's already there. So why can't owtf just use whats there already?
Looks like owtf installer script in Kali2 now broken.

**Comment by delta24** [comment]
Looks like Kali issue/feature - they have `chown` the packages directory so that it doesn't break the other tools.
Let me see and come up with a new installation method, preferably using `virtualenv` :)

**Comment by delta24** [comment]
Duplicate #516
