### ISSUE TITLE
Proxy worker dies unexpectedly with Uncaught Exception 

### ISSUE THREAD

**Issue by urand0m** [owtf/owtf#752]
## Current Behavior

During the arachni phase of web application scanning the proxy located on port 8008 dies unexpectedly and doesn't accept any new connection.
## Steps to Reproduce (for bugs)

Just start a worker on target http://testphp.acunetix.com
## Logs

```
[ERROR] [2016-09-30 14:36:28,101] [File 'web.py', line 1811, in log_request] - 500 GET http://192.168.254.19:8081/secured/62b49ff9ae71f2e23aa4f631d0844276f4673a8c/ (127.0.0.1) 30074.67ms
[ERROR] [2016-09-30 14:36:28,101] [File 'web.py', line 1407, in log_exception] - Uncaught exception GET http://192.168.254.19:8081/secured/62b49ff9ae71f2e23aa4f631d0844276f4673a8c/ (127.0.0.1)
HTTPServerRequest(protocol='http', host='192.168.254.19:8081', method='GET', uri='http://192.168.254.19:8081/secured/62b49ff9ae71f2e23aa4f631d0844276f4673a8c/', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Host': '192.168.254.19:8081', 'Accept-Language': 'en-US,en;q=0.8,he;q=0.6', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,_/_;q=0.8', 'User-Agent': 'Mozilla/5.0 (X11; Linux i686; rv:6.0) Gecko/20100101 Firefox/6.0'})
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1288, in _stack_context_handle_exception
    raise_exc_info((type, value, traceback))
  File "/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py", line 314, in wrapped
    ret = fn(_args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1484, in future_complete
    f.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 109, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 633, in run
    yielded = self.gen.send(value)
  File "/root/owtf/framework/http/proxy/proxy.py", line 125, in get
    self.cached_response = self.cache_handler.load()
  File "/root/owtf/framework/http/proxy/cache_handler.py", line 119, in load
    self.file_lock.acquire()
  File "/root/owtf/framework/lib/filelock.py", line 53, in acquire
    raise FileLockTimeoutException("%d seconds passed." % self.timeout)
FileLockTimeoutException: 30 seconds passed.
```

## Context

The issue causes or arachni to fail the scan due to timeout or missing some resource during the web application scanning phase
## Your Environment
- Installation method used:  bootstrap.sh 
- Operating System and version:  Kali
- pip/setuptools version: pip 8.1.2 from /usr/lib/python2.7/dist-packages (python 2.7)
- sudo access: no, root access

**Comment by delta24** [comment]
@urand0m This is known issue - proxy cache locking due to Tornado errors and timeouts. 
@DarKnight24 can you take a look?

**Comment by viyatb** [comment]
Fixed in https://github.com/owtf/owtf/tree/new-arch.
