### ISSUE TITLE
Default installation fails to properly setup sslabs

### ISSUE THREAD

**Issue by 7a** [owtf/owtf#773]
NOTE: Tried on UI Improvements branch (please merge fix there for next round! ;)

The SSL Labs tool is installed without errors but the SSL active plugin returns the following output, which means that something is wrong, not properly setup?:

```
Segmentation fault
Traceback (most recent call last):
  File "/root/owtf/scripts/ssl/reporter.py", line 9, in <module>
    data = json.load(data_file)
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by delta24** [comment]
@7a Their JSON format probably changed - breaking the parser.
@DarKnight24 ?
