### ISSUE TITLE
how install in my mac os 10.12.2

### ISSUE THREAD

**Issue by hktalent** [owtf/owtf#796]
how install in my mac os 10.12.2
1、 wget -N https://raw.githubusercontent.com/owtf/bootstrap-script/master/bootstrap.sh; bash bootstrap.sh

2、error
`sudo pip2 install --upgrade cffi
The directory '/Users/xiatian/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/xiatian/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting cffi
  Could not find a version that satisfies the requirement cffi (from versions: )
No matching distribution found for cffi
[*] Running following command
sudo -E pip2 install --upgrade -r /Users/xiatian/safe/owtf/install/owtf.pip
The directory '/Users/xiatian/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/xiatian/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting beautifulsoup4==4.3.2 (from -r /Users/xiatian/safe/owtf/install/owtf.pip (line 6))
  Downloading beautifulsoup4-4.3.2.tar.gz (143kB)
    42% |█████████████▊                  | 61kB 225bytes/s eta 0:06:04Exception:
Traceback (most recent call last):
  File "/Users/xiatian/.pyenv/versions/2.7.13/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Users/xiatian/.pyenv/versions/2.7.13/lib/python2.7/site-packages/pip/commands/install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "/Users/xiatian/.pyenv/versions/2.7.13/lib/python2.7/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/Users/xiatian/.pyenv/versions/2.7.13/lib/python2.7/site-packages/pip/req/req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "/Users/xiatian/.pyenv/versions/2.7.13/lib/python2.7/site-packages/pip/download.py", line 821, in unpack_url
    hashes=hashes
  File "/Users/xiatian/.pyenv/versions/2.7.13/lib/python2.7/site-packages/pip/download.py", line 659, in unpack_http_url
    hashes)
  File "/Users/xiatian/.pyenv/versions/2.7.13/lib/python2.7/site-packages/pip/download.py", line 882, in _download_http_url
    _download_url(resp, link, content_file, hashes)
  File "/Users/xiatian/.pyenv/versions/2.7.13/lib/python2.7/site-packages/pip/download.py", line 603, in _download_url
    hashes.check_against_chunks(downloaded_chunks)
  File "/Users/xiatian/.pyenv/versions/2.7.13/lib/python2.7/site-packages/pip/utils/hashes.py", line 46, in check_against_chunks
    for chunk in chunks:
  File "/Users/xiatian/.pyenv/versions/2.7.13/lib/python2.7/site-packages/pip/download.py", line 571, in written_chunks
    for chunk in chunks:
  File "/Users/xiatian/.pyenv/versions/2.7.13/lib/python2.7/site-packages/pip/utils/ui.py", line 139, in iter
    for x in it:
  File "/Users/xiatian/.pyenv/versions/2.7.13/lib/python2.7/site-packages/pip/download.py", line 560, in resp_read
    decode_content=False):
  File "/Users/xiatian/.pyenv/versions/2.7.13/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/response.py", line 357, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/Users/xiatian/.pyenv/versions/2.7.13/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/response.py", line 324, in read
    flush_decoder = True
  File "/Users/xiatian/.pyenv/versions/2.7.13/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/xiatian/.pyenv/versions/2.7.13/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/response.py", line 246, in _error_catcher
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
ReadTimeoutError: HTTPSConnectionPool(host='pypi.python.org', port=443): Read timed out.
[*] Running following command
sudo sh /Users/xiatian/safe/owtf/scripts/db_setup.sh init
readlink: illegal option -- f
usage: readlink [-n] [file ...]
grep: ./framework/config/framework_config.cfg: No such file or directory

^C[*] Running following command
sudo sh /Users/xiatian/safe/owtf/scripts/db_run.sh
readlink: illegal option -- f
usage: readlink [-n] [file ...]
grep: ./framework/config/framework_config.cfg: No such file or directory
Default file  does not exist
Rerun script with path parameter. Usage : /Users/xiatian/safe/owtf/scripts/db_run.sh [db_config_file_path]
`

**Comment by delta24** [comment]
@hktalent as of right now, Mac OS is not supported. But you can use Docker or a Kali Linux VM to install this.
