### ISSUE TITLE
Travis is failing again

### ISSUE THREAD

**Issue by DePierre** [owtf/owtf#807]
Since 46f305b2e3ec85849b149053d715a60ee6509ac3, it appears that Travis is failing again (see https://travis-ci.org/owtf/owtf/builds/195367688).

This time with the following traceback during `pip` installation:

```py3tb
Collecting pyparsing (from packaging>=16.8->setuptools->PyHamcrest==1.9.0->-r ./owtf_testing/owtf_testing.pip (line 1))
  Using cached pyparsing-2.1.10-py2.py3-none-any.whl
Installing collected packages: six, appdirs, pyparsing, packaging, setuptools, PyHamcrest, backports.ssl-match-hostname, singledispatch, certifi, backports-abc, tornado, funcsigs, pbr, mock
  Found existing installation: six 1.10.0
    Uninstalling six-1.10.0:
      Successfully uninstalled six-1.10.0
  Rolling back uninstall of six
Exception:
Traceback (most recent call last):
  File "/home/travis/.virtualenvs/owtf/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/travis/.virtualenvs/owtf/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/home/travis/.virtualenvs/owtf/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/home/travis/.virtualenvs/owtf/lib/python2.7/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/home/travis/.virtualenvs/owtf/lib/python2.7/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/home/travis/.virtualenvs/owtf/lib/python2.7/site-packages/pip/wheel.py", line 247, in move_wheel_files
    prefix=prefix,
  File "/home/travis/.virtualenvs/owtf/lib/python2.7/site-packages/pip/locations.py", line 140, in distutils_scheme
    d = Distribution(dist_args)
  File "/home/travis/.virtualenvs/owtf/lib/python2.7/site-packages/setuptools/dist.py", line 320, in __init__
    _Distribution.__init__(self, attrs)
  File "/opt/python/2.7.12/lib/python2.7/distutils/dist.py", line 287, in __init__
    self.finalize_options()
  File "/home/travis/.virtualenvs/owtf/lib/python2.7/site-packages/setuptools/dist.py", line 386, in finalize_options
    ep.require(installer=self.fetch_build_egg)
  File "/home/travis/.virtualenvs/owtf/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2318, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/travis/.virtualenvs/owtf/lib/python2.7/site-packages/pkg_resources/__init__.py", line 862, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
  File "/home/travis/.virtualenvs/owtf/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2562, in requires
    dm = self._dep_map
  File "/home/travis/.virtualenvs/owtf/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2809, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/home/travis/.virtualenvs/owtf/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2818, in _compute_dependencies
    for req in self._parsed_pkg_info.get_all('Requires-Dist') or []:
  File "/home/travis/.virtualenvs/owtf/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2800, in _parsed_pkg_info
    metadata = self.get_metadata(self.PKG_INFO)
  File "/home/travis/.virtualenvs/owtf/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1468, in get_metadata
    value = self._get(self._fn(self.egg_info, name))
  File "/home/travis/.virtualenvs/owtf/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1577, in _get
    with open(path, 'rb') as stream:
IOError: [Errno 2] No such file or directory: '/home/travis/.virtualenvs/owtf/lib/python2.7/site-packages/six-1.10.0.dist-info/METADATA
```

@delta24 Do you know if it is related to your commit specifically? Or is it pip?

**Comment by DePierre** [comment]
Seems to be related to pip or at least something independent to OWTF. I re-run an older travis build that was successful and it is now failing as well (see https://travis-ci.org/owtf/owtf/builds/194497121).

Anyone could investigate?

**Comment by DarKnight24** [comment]
@delta24 @DePierre It seems travis is failing due to pip. Removing "--force-reinstall" from the command fixes it.

**Comment by DePierre** [comment]
@DarKnight24 @delta24 So what should we do? Should we remove the `--force-reinstall` option? Will it break something else?

**Comment by delta24** [comment]
@DePierre I think removing `--force-reinstall` is a safe option.

**Comment by delta24** [comment]
@DePierre Still failing - although now something is wrong with Skipfish.

**Comment by DePierre** [comment]
@delta24 I've re-run the travis build for 0f95c2f. If it succeeds again, the issue with skipfish might have been introduced in the commits after 0f95c2f.

**Comment by DePierre** [comment]
@delta24 Since restarting the build on 0f95c2f succeeded and faa82f0 failed systematically, I would assume that faa82f0 broke Skipfish somehow.

Is it possible that the `sudo` command changed some paths? Or that `"$apt_wrapper_path"` did something about Skipfish?

**Comment by DePierre** [comment]
@DarKnight24 So the `sudo`? I mean there is no magic here. 0f95c2f is 100% successful and faa82f0 is 0% successful. Therefore faa82f0 must have introduced the thing that makes Travis fail.

If it is not the `$apt_wrapper_path`, then it's the `sudo` since there are only two lines changed by faa82f0. What does the `sudo` do?

**Comment by DarKnight24** [comment]
Earlier `sudo`was missing so pref.sh was not running. So it has something to do.

**Comment by DePierre** [comment]
@DarKnight24 @delta24 So any update regarding Travis? Why is faa82f0 breaking the build?

**Comment by delta24** [comment]
@DePierre looks like we throw https://wiki.debian.org/DontBreakDebian out of the window here and IMO this is why it broke.

**Comment by DePierre** [comment]
@delta24 Should we revert the commit then? Or say goodbye to Travis and stop running the functional tests?

**Comment by delta24** [comment]
@DePierre do the functional tests use any other tool than Skipfish?

**Comment by DePierre** [comment]
@delta24 Yes. I believe that Arachni is used as well and maybe a couple others. I mean whatever the case is, the install **should** be working like it used to.

Do we need that commit? What does it provide? What wasn't working before? What has been changed?

**Comment by delta24** [comment]
I think we can safely remove that commit. The `pref.sh` file basically gives preferences to the Debian repository before Kali one. Can you make a pull request removing it - that would give us an idea how Travis responds?

**Comment by delta24** [comment]
Closed in https://github.com/owtf/owtf/pull/818.
