### ISSUE TITLE
Installation script on Kali

### ISSUE THREAD

**Issue by benoitmaudet** [owtf/owtf#812]
The installation on Kali (4.6.0-kali1-amd64 ) doesn't work. I have just downloaded the last version of Kali and launched: 
`wget -N https://raw.githubusercontent.com/owtf/bootstrap-script/master/bootstrap.sh; bash bootstrap.sh`

Then, when I do : 
`./owtf/owtf.py`

 I get the error : 
`
./owtf.py 
Traceback (most recent call last):
  File "./owtf.py", line 17, in <module>
    from framework.core import Core
  File "/root/owtf/framework/core.py", line 21, in <module>
    from framework.http.proxy import proxy, transaction_logger
  File "/root/owtf/framework/http/proxy/proxy.py", line 31, in <module>
    from socket_wrapper import wrap_socket
  File "/root/owtf/framework/http/proxy/socket_wrapper.py", line 9, in <module>
    from gen_cert import gen_signed_cert
  File "/root/owtf/framework/http/proxy/gen_cert.py", line 6, in <module>
    from OpenSSL import crypto
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 105, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'
`

**Comment by delta24** [comment]
@benoitmaudet are you using the latest Kali rolling version?

**Comment by mlinton** [comment]
I am also getting this same error - I have run pip install --upgrade pyopenssl and confirmed that I have pyopenssl-16.2.0 installed.

**Comment by delta24** [comment]
@mlinton @benoitmaudet how did you install Kali ? Did you use the Kali light VM? I think there is a similar problem with it.

**Comment by benoitmaudet** [comment]
@delta24 I used this one : https://images.offensive-security.com/virtual-images/Kali-Linux-2016.2-vm-amd64.7z

**Comment by delta24** [comment]
@benoitmaudet @mlinton I downloaded the Kali Linux virtualbox image from the above link and upgraded the Kali installation using

```
apt-get install update
apt-get install dist-upgrade
```
and installed OWTF. I did not get any errors and OWTF starts up perfectly fine.
Please upgrade the Kali installation and try installing OWTF again.

**Comment by hktalent** [comment]
do
apt-get update; apt-get upgrade;apt-get dist-upgrade;
but the same
# ./owtf.py 
Traceback (most recent call last):
  File "./owtf.py", line 12, in <module>
    from framework.dependency_check import verify_dependencies
  File "/usr/share/owtf/framework/dependency_check.py", line 12, in <module>
    import pip
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 21, in <module>
    from pip._vendor.requests.packages.urllib3.exceptions import DependencyWarning
  File "/usr/lib/python2.7/dist-packages/pip/_vendor/__init__.py", line 64, in <module>
    vendored("cachecontrol")
  File "/usr/lib/python2.7/dist-packages/pip/_vendor/__init__.py", line 36, in vendored
    __import__(modulename, globals(), locals(), level=0)
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/__init__.py", line 9, in <module>
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/wrapper.py", line 1, in <module>
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/adapter.py", line 4, in <module>
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/__init__.py", line 52, in <module>
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/packages/__init__.py", line 59, in <module>
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/packages/__init__.py", line 32, in vendored
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/contrib/pyopenssl.py", line 47, in <module>
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 105, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'
