### ISSUE TITLE
in kali Linux 4.6.0-kali1-amd64 #1 SMP Debian 4.6.4-1kali1 (2016-07-21) x86_64 GNU/Linux

### ISSUE THREAD

**Issue by doglife007** [owtf/owtf#833]
Traceback (most recent call last):
  File "./owtf.py", line 13, in <module>
    from framework.dependency_check import verify_dependencies
  File "/root/Downloads/owtf/framework/dependency_check.py", line 11, in <module>
    import pip
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 21, in <module>
    from pip._vendor.requests.packages.urllib3.exceptions import DependencyWarning
  File "/usr/lib/python2.7/dist-packages/pip/_vendor/__init__.py", line 64, in <module>
    vendored("cachecontrol")
  File "/usr/lib/python2.7/dist-packages/pip/_vendor/__init__.py", line 36, in vendored
    __import__(modulename, globals(), locals(), level=0)
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/__init__.py", line 9, in <module>
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/wrapper.py", line 1, in <module>
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/adapter.py", line 4, in <module>
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/__init__.py", line 52, in <module>
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/packages/__init__.py", line 59, in <module>
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/packages/__init__.py", line 32, in vendored
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/contrib/pyopenssl.py", line 47, in <module>
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 105, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'

**Comment by DarKnight24** [comment]
@doglife007 run `sudo pip install -U pyopenssl` to remove the error.

**Comment by jack17529** [comment]
We have already mentioned the previous requirements to install owtf. please check.
Please keep your kali updated and upgraded .

**Comment by doglife007** [comment]
my kali is all update & upgrade  but same to be problem whit  pyopenssl 
i try   to remover the error whit sudo pip install -U pyopenssl but not work ... 
pip install -U pyopenssl
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    from pip import main
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 21, in <module>
    from pip._vendor.requests.packages.urllib3.exceptions import DependencyWarning
  File "/usr/lib/python2.7/dist-packages/pip/_vendor/__init__.py", line 64, in <module>
    vendored("cachecontrol")
  File "/usr/lib/python2.7/dist-packages/pip/_vendor/__init__.py", line 36, in vendored
    __import__(modulename, globals(), locals(), level=0)
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/__init__.py", line 9, in <module>
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/wrapper.py", line 1, in <module>
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/adapter.py", line 4, in <module>
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/__init__.py", line 52, in <module>
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/packages/__init__.py", line 59, in <module>
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/packages/__init__.py", line 32, in vendored
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/contrib/pyopenssl.py", line 47, in <module>
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 105, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'

**Comment by DarKnight24** [comment]
@doglife007 can you share complete logs using pastebin.

**Comment by jack17529** [comment]
@doglife007  check this please - https://forums.kali.org/showthread.php?35031-Python-AttributeError-module-object-has-no-attribute-SSL_ST_INIT

**Comment by doglife007** [comment]
jack17529 in this post i only see update update upgrade  ... :) 
and my Reading state information... Done

> virtualenv is already the newest version (15.1.0+ds-1).
> virtualenvwrapper is already the newest version (4.3.1-2).
> python-openssl is already the newest version (16.2.0-1)
> libffi-dev is already the newest version (3.2.1-6).
> libffi-dev set to manually installed.
> libssl-dev is already the newest version (1.1.0e-1).
> python-dev is already the newest version (2.7.13-2).
> pip --version
pip 9.0.1 from /usr/local/lib/python2.7/dist-packages/pip-9.0.1-py2.7.egg (python 2.7)

i give up !!  on owtf
Thanks for the replies
Once again, appreciate all the feedback.

**Comment by viyatb** [comment]
@doglife007 did you do
`source .<shell>rc; workon owtf`? You have to manually switch on the OWTF virtualenv using `workon owtf` everytime you want to run OWTF.

**Comment by doglife007** [comment]
viyatb: workon seems to work  but don't really like it !!

**Comment by viyatb** [comment]
@doglife007 There's no way around it. Kali Linux does not allow tools to modify the system Python environment.
