### ISSUE TITLE
SQL exception in file-server

### ISSUE THREAD

**Issue by jaylinski** [owtf/owtf#850]
I can't seem to get workers to pick up jobs from the worklist.

## Expected Behavior
Docker image works out of the box, workers pick up tasks from worklist.

## Current Behavior
Exceptions in file-server are thrown.   
Workers are not picking up tasks from worklist.

## Steps to Reproduce (for bugs)
1. Build and start docker image as described in https://github.com/owtf/owtf-docker
2. Add target and a run a plugin (add something to the worklist)

## Logs

1. Connect to container via `docker run -it <container_name> bash`
2. Check file-server log via `tail -f /tmp/owtf/file_server.log`.

```
StatementError: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back [SQL: u'SELECT configuration.key AS configuration_key, configuration.value AS configuration_value, configuration.section AS configuration_section, configuration.descrip AS configuration_descrip, configuration.dirty AS configuration_dirty \nFROM configuration \nWHERE configuration.key = %(param_1)s'] [parameters: [{'%(139842964893904 param)s': 'MIN_RAM_NEEDED'}]]
[E 170508 12:25:06 ioloop:638] Exception in callback <bound method WorkerManager.manage_workers of <framework.plugin.worker_manager.WorkerManager instance at 0x7f2fba432758>>
    Traceback (most recent call last):
      File "/root/.virtualenvs/owtf/lib/python2.7/site-packages/tornado/ioloop.py", line 1026, in _run
        return self.callback()
      File "/owtf/framework/plugin/worker_manager.py", line 124, in manage_workers
        work_to_assign = self.get_task()
      File "/owtf/framework/plugin/worker_manager.py", line 69, in get_task
        if int(free_mem) > int(self.db_config.Get('MIN_RAM_NEEDED')):
      File "/owtf/framework/db/config_manager.py", line 52, in Get
        obj = self.db.session.query(models.ConfigSetting).get(Key)
      File "/root/.virtualenvs/owtf/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 864, in get
        return self._get_impl(ident, loading.load_on_ident)
      File "/root/.virtualenvs/owtf/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 897, in _get_impl
        return fallback_fn(self, key)
      File "/root/.virtualenvs/owtf/lib/python2.7/site-packages/sqlalchemy/orm/loading.py", line 223, in load_on_ident
        return q.one()
      File "/root/.virtualenvs/owtf/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2814, in one
        ret = self.one_or_none()
      File "/root/.virtualenvs/owtf/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2784, in one_or_none
        ret = list(self)
      File "/root/.virtualenvs/owtf/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2855, in __iter__
        return self._execute_and_instances(context)
      File "/root/.virtualenvs/owtf/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2878, in _execute_and_instances
        result = conn.execute(querycontext.statement, self._params)
      File "/root/.virtualenvs/owtf/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 945, in execute
        return meth(self, multiparams, params)
      File "/root/.virtualenvs/owtf/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
        return connection._execute_clauseelement(self, multiparams, params)
      File "/root/.virtualenvs/owtf/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
        compiled_sql, distilled_params
      File "/root/.virtualenvs/owtf/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1121, in _execute_context
        None, None)
      File "/root/.virtualenvs/owtf/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
        exc_info
      File "/root/.virtualenvs/owtf/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
        reraise(type(exception), exception, tb=exc_tb, cause=cause)
      File "/root/.virtualenvs/owtf/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1114, in _execute_context
        conn = self._revalidate_connection()
      File "/root/.virtualenvs/owtf/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 424, in _revalidate_connection
        "Can't reconnect until invalid "
```
OWTF started without errors:
```
docker run -it -p 8008:8008 -p 8009:8009 -p 8010:8010 owtf-master /bin/bash
Starting the postgresql service
[ ok ] Starting PostgreSQL 9.6 database server: main.
CREATE ROLE
CREATE DATABASE

 _____ _ _ _ _____ _____
|     | | | |_   _|   __|
|  |  | | | | | | |   __|
|_____|_____| |_| |__|

        @owtfp
    http://owtf.org
    
[*] OWTF Version: 2.1a, Release: Chicken Korma (Alpha) 
[-] Loading framework please wait..
[-] Loading Resources from: /root/.owtf/configuration/resources.cfg..
[-] Loading Mapping from: /root/.owtf/configuration/mappings.cfg..
[*] 0.0.0.0:8008 <-- HTTP(S) Proxy to which requests can be directed
[*] http://0.0.0.0:8009 <-- Web UI URL
[-] Press Ctrl+C when you spawned a shell ;)
```

## Your Environment

* Installation method used: Docker
* Version/branch used: develop
* Operating System and version: macOS Sierra
* Docker Memory limit: 2GB
* pip/setuptools version:
* sudo access: 

What am I missing?

**Comment by viyatb** [comment]
@jaylinski Thanks for reporting the issue! I am investigating whether the bug was introduced in part by me in f2b11188548832d1400ecb4a871f49b423d677f5.

**Comment by jaylinski** [comment]
@viyatb Thanks! Anything I can help you with?

**Comment by viyatb** [comment]
@jaylinski The core issue is that OWTF uses multiprocessing and SQLAlchemy+psycopg2 combination needs to be tweaked carefully to have deadlock free transactions. We used `NullPool` (which essentially means that there are no queues). We shifted to `QueuePool` a while back along with some fixes for multiprocessing. 
We still had some problems due to deadlocks, so I reverted the codebase back to use NullPool. I think I need to remove the `register_after_fork` line (which was the fix for QueuePool).

[This](http://docs.sqlalchemy.org/en/latest/core/pooling.html) is a nice read if you want to go to the root of the problem. I have some project deadlines till May 12, so I probably will investigate and push the fix after that.

**Comment by viyatb** [comment]
@jaylinski I can't reproduce this - more evidence that this is some race condition/wierd deadlock.
Can you try again and check if that error occurs?

**Comment by jaylinski** [comment]
@viyatb :thinking: I just reproduced this on my Ubuntu 16.04 64bit machine. (So it is not a problem with macOS).

Like I said, I built a fresh docker-image via
```
$ git clone https://github.com/owtf/owtf-docker.git
$ docker build -t owtf-local .
$ docker run -it -p 8008:8008 -p 8009:8009 -p 8010:8010 owtf-local /bin/bash
```
As soon as I submit a task to the worklist, the exception occurs...

What host-system are you using to build and run the docker-image?

**Comment by viyatb** [comment]
@jaylinski same Docker on macOS.

**Comment by jaylinski** [comment]
@viyatb I debugged it further.

I built the image with commit 5f15a5c72cbf3103ccbf378a61d825dd4fe161f9 (the one before the db-pool change). Same problem.

The exception is thrown as soon as I press the "Run"-button in `/ui/targets/`. This request causes the exception: `http://localhost:8009/api/plugins/?group=web&group=network&_=1494790943076`.

There is also an exception entry in `ui_server.log`:
```
[W 170514 20:05:50 web:1971] 404 GET /static/fonts/glyphicons-halflings-regular.woff2 (172.17.0.1) 1.24ms
[E 170514 20:05:50 pool:696] Exception during reset or similar
    Traceback (most recent call last):
      File "/root/.virtualenvs/owtf/lib/python2.7/site-packages/sqlalchemy/pool.py", line 687, in _finalize_fairy
        fairy._reset(pool)
      File "/root/.virtualenvs/owtf/lib/python2.7/site-packages/sqlalchemy/pool.py", line 829, in _reset
        pool._dialect.do_rollback(self)
      File "/root/.virtualenvs/owtf/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 440, in do_rollback
        dbapi_connection.rollback()
    DatabaseError: SSL error: decryption failed or bad record mac
    
[I 170514 20:05:50 web:1971] 200 GET /api/plugins/?group=web&group=network&_=1494792346265 (172.17.0.1) 265.54ms
```

I made sure the latest version of sqlalchemy (1.1.9) is installed inside the docker image by running `/owtf/install# pip2 install --upgrade -r owtf.pip`, committing the image and restarting it.

I also tried turning off postgres `ssl`, but it did only fix the exception in `ui_server.log`.

Could be related to celery/celery/issues/1564?

But this should not be an issue because of your fix here https://github.com/owtf/owtf/blob/f2b11188548832d1400ecb4a871f49b423d677f5/framework/db/db.py#L134

**Comment by jaylinski** [comment]
@viyatb I guess something goes wrong while the image is built.

Could you please upload the latest release to the Docker Hub (https://hub.docker.com/r/owtf/owtf/tags/)? Thank you!

**Comment by viyatb** [comment]
@jaylinski ok, let me try that :)

**Comment by jaylinski** [comment]
@viyatb Thank you, please ping me when the upload is done. I'll give it a try. :)

**Comment by viyatb** [comment]
@jaylinski I think the problem is with `ssl=true` in the `postgresql.conf`. I'll add it to the `postgres_entry.sh` tonight.

**Comment by viyatb** [comment]
@jaylinski that did solved the problem. I haven't pushed out the built image yet, but you can use the Docker container which maps to the source on local disk as a workaround for now. The readme explains you the details. 
Let me know if you have any problems with that.

**Comment by jaylinski** [comment]
@viyatb Can confirm! :tada: 

Looking forward for you pushing the fixed image. Thank you!
