### ISSUE TITLE
TypeError in Wapiti Unauthenticated plugin

### ISSUE THREAD

**Issue by DePierre** [owtf/owtf#863]
Running the `Wapiti_Unauthenticated` plugin throws a `TypeError` in wapitiCore/language/language.py

OWTF:
```bash
Starting the postgresql service
[ ok ] Starting PostgreSQL 9.6 database server: main.
Restarting the postgresql service
[ ok ] Restarting PostgreSQL 9.6 database server: main.
CREATE ROLE
CREATE DATABASE

 _____ _ _ _ _____ _____
|     | | | |_   _|   __|
|  |  | | | | | | |   __|
|_____|_____| |_| |__|

        @owtfp
    http://owtf.org
    
[*] OWTF Version: 2.1a, Release: Chicken Korma (Alpha) 
[-] Loading framework please wait..
[-] Loading Resources from: /root/.owtf/configuration/resources.cfg..
[-] Loading Mapping from: /root/.owtf/configuration/mappings.cfg..
[*] 0.0.0.0:8008 <-- HTTP(S) Proxy to which requests can be directed
[*] http://0.0.0.0:8009 <-- Web UI URL
[-] Press Ctrl+C when you spawned a shell ;)
[-] __________ 1 - Target: http://192.168.1.59 -> Plugin: Visit Urls (web/active) __________
[-] 0 URLs were visited
[-] __________ 2 - Target: http://192.168.1.59 -> Plugin: Application Discovery (web/active) __________
[-] 
[-] Executing :

[ . . . ]


cd owtf_review/targets/http__192.168.1.59/partial/Wapiti_Unauthenticated/active;sh /owtf/scripts/run_wapiti.sh /usr/bin/wapiti http://192.168.1.59

[-] 
[-] ------> Execution Start Date/Time: 31/07/2017-11:49
[-] 
[*] [*] Running: /usr/bin/wapiti http://192.168.1.59 -f xml --output wapiti_report2017-07-31_11_49_44.xml
[*] Traceback (most recent call last):
[*] File "/usr/bin/wapiti", line 41, in <module>
[*] lan.configure()
[*] File "/usr/lib/python2.7/dist-packages/wapitiCore/language/language.py", line 58, in configure
[*] lang = langCounty[:2]  # en
[*] TypeError: 'NoneType' object has no attribute '__getitem__'
[-] Time=0s,  67ms
```

Setup:
```
---> Starting metasploitable2
-> ip 192.168.1.59
----> on web app : target view : add target 192.168.1.59
----> click on ip address
----> click on run plugins
----> click on launch in group - web - active - RUN
```

Thanks @nico34 for reporting the issue

**Comment by viyatb** [comment]
@DePierre @nico34 I cannot reproduce this. Maybe this is a language/locale problem (distro related)?

**Comment by DePierre** [comment]
@viyatb No idea. IMO looking at the error, it's a Wapiti issue anyway and should be reported upstream.

**Comment by viyatb** [comment]
@DePierre agreed. I'll do that.

**Comment by DePierre** [comment]
As discussed, this issue is related to Wapiti and should be fixed upstream. Since Wapiti is abandoned, there is not much we can do, except recommending updating the Kali machine, hoping that it would fix the issue.

Closing.
