### ISSUE TITLE
LoadError in Arachni_Unauthenticated

### ISSUE THREAD

**Issue by DePierre** [owtf/owtf#864]
Running the `Arachni_Unauthenticated` plugin throws a `LoadError ` in arachni.

OWTF:
```bash
Starting the postgresql service
[ ok ] Starting PostgreSQL 9.6 database server: main.
Restarting the postgresql service
[ ok ] Restarting PostgreSQL 9.6 database server: main.
CREATE ROLE
CREATE DATABASE

 _____ _ _ _ _____ _____
|     | | | |_   _|   __|
|  |  | | | | | | |   __|
|_____|_____| |_| |__|

        @owtfp
    http://owtf.org
    
[*] OWTF Version: 2.1a, Release: Chicken Korma (Alpha) 
[-] Loading framework please wait..
[-] Loading Resources from: /root/.owtf/configuration/resources.cfg..
[-] Loading Mapping from: /root/.owtf/configuration/mappings.cfg..
[*] 0.0.0.0:8008 <-- HTTP(S) Proxy to which requests can be directed
[*] http://0.0.0.0:8009 <-- Web UI URL
[-] Press Ctrl+C when you spawned a shell ;)
[-] __________ 1 - Target: http://192.168.1.59 -> Plugin: Visit Urls (web/active) __________
[-] 0 URLs were visited
[-] __________ 2 - Target: http://192.168.1.59 -> Plugin: Application Discovery (web/active) __________
[-] 
[-] Executing :

[ . . . ]



cd owtf_review/targets/http__192.168.1.59/partial/Arachni_Unauthenticated/active;sh /owtf/scripts/run_arachni.sh /usr/share/arachni/bin/arachni /usr/share/arachni/bin/arachni_reporter http://192.168.1.59 '0.0.0.0:8008' 'Mozilla/5.0 (X11; Linux i686; rv:6.0) Gecko/20100101 Firefox/15.0'


[-] 
[-] ------> Execution Start Date/Time: 31/07/2017-11:49
[-] 
[*] DATE=2017-07-31_11_49_18
[*] 
[*] [*] Running: /usr/share/arachni/bin/arachni --http-user-agent="Mozilla/5.0 (X11; Linux i686; rv:6.0) Gecko/20100101 Firefox/6.0" --http-request-concurrency=20 --report-save-path="arachni_report2017-07-31_11_49_18.afr" --http-proxy=0.0.0.0:8008 http://192.168.1.59
[*] /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- concurrent (LoadError)
[*] from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
[*] from /usr/share/arachni/lib/arachni.rb:11:in `<top (required)>'
[*] from /usr/share/arachni/ui/cli/framework.rb:9:in `require_relative'
[*] from /usr/share/arachni/ui/cli/framework.rb:9:in `<top (required)>'
[*] from /usr/share/arachni/bin/arachni:10:in `require_relative'
[*] from /usr/share/arachni/bin/arachni:10:in `<main>'
[*] 
[*] [*] Running: /usr/share/arachni/bin/arachni_reporter --reporter="html:outfile=arachni_report2017-07-31_11_49_18.html.zip" --reporter="txt:outfile=arachni_report2017-07-31_11_49_18.txt" --reporter="json:outfile=arachni_report2017-07-31_11_49_18.json" --reporter="ap:outfile=arachni_report2017-07-31_11_49_18.ap" --reporter="xml:outfile=arachni_report2017-07-31_11_49_18.xml" "/owtf_review/targets/http__192.168.1.59/partial/Arachni_Unauthenticated/active/arachni_report2017-07-31_11_49_18.afr"
[*] /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- concurrent (LoadError)
[*] from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
[*] from /usr/share/arachni/lib/arachni.rb:11:in `<top (required)>'
[*] from /usr/share/arachni/ui/cli/reporter.rb:9:in `require_relative'
[*] from /usr/share/arachni/ui/cli/reporter.rb:9:in `<top (required)>'
[*] from /usr/share/arachni/bin/arachni_reporter:10:in `require_relative'
[*] from /usr/share/arachni/bin/arachni_reporter:10:in `<main>'
[*] unzip:  cannot find or open arachni_report2017-07-31_11_49_18.html.zip, arachni_report2017-07-31_11_49_18.html.zip.zip or arachni_report2017-07-31_11_49_18.html.zip.ZIP.
[*] [*] Removing potential binary garbage from text report ..
[*] strings: 'arachni_report2017-07-31_11_49_18.txt': No such file
[*] 
[*] [*] Done!
```

Setup:
```
---> Starting metasploitable2
-> ip 192.168.1.59
----> on web app : target view : add target 192.168.1.59
----> click on ip address
----> click on run plugins
----> click on launch in group - web - active - RUN
```

Thanks @nico34 for reporting the issue

**Comment by viyatb** [comment]
@DePierre @nico34 Thanks for the report! I have noticed this issue only recently, so it must have been change in the arachni's CLI flags or configuration script. I'll have a look at this.

**Comment by viyatb** [comment]
On a closer look, this has something to do with Ruby configuration on Kali. Seems like they broke it.

**Comment by DePierre** [comment]
@viyatb Do you know if they are going to fix it? Or should we wait for Arachni to fix it? Or something else?

**Comment by viyatb** [comment]
@DePierre we report it upstream and wait.

**Comment by Tikam02** [comment]
I checked the files for errors for "require_relative" that's for path and top<required> i think that was correct.
and also checked for soltuions and here i got that it has some ruby files problem. 
https://bugs.kali.org/view.php?id=3306

I think they also got same issues, but In Arachni it was closed.
https://github.com/Arachni/arachni/issues/227
https://github.com/Arachni/arachni/issues/874
https://github.com/Arachni/arachni/issues/474

**Comment by viyatb** [comment]
Closing as fixed upstream - https://bugs.kali.org/view.php?id=3306.
