### ISSUE TITLE
[Errno 2] No such file or directory: '/root/.owtf/db.cfg'.

### ISSUE THREAD

**Issue by zzhiqi54** [owtf/owtf#903]
Traceback (most recent call last):
  File "install/install.py", line 136, in <module>              install_restricted_from_cfg(restricted_cfg)               File "install/install.py", line 85, in install_restricted_from_cfg                                                        install_in_directory(os.path.expanduser(cp.get(section, "directory")), cp.get(section, "command"))                    File "/usr/lib/python2.7/dist-packages/backports/configparser/__init__.py", line 811, in get
    d)
  File "/usr/lib/python2.7/dist-packages/backports/configparser/__init__.py", line 384, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)                                                File "/usr/lib/python2.7/dist-packages/backports/configparser/__init__.py", line 425, in _interpolate_some
    if "%" in v:
TypeError: argument of type 'int' is not iterable
root@kali:/home/Scanner/owtf# owtf
_____ _ _ _ _____ _____                                    |     | | | |_   _|   __|
|  |  | | | | | | |   __|
|_____|_____| |_| |__|                                                                                                          @owtfp                                                  http://owtf.org                                                                                                     [-] Loading config from: /root/.owtf/conf/framework.cfg..
ERROR:root:Aborted by Framework: Error when calling 'open'! [Errno 2] No such file or directory: '/root/.owtf/db.cfg'.

**Comment by viyatb** [comment]
@zzhiqi54 what version of OWTF are you running?

**Comment by viyatb** [comment]
Closing this issue since there is no response.

**Comment by sdcampbell** [comment]
Hi, I'm experiencing the same error. I'm on Kali Linux 2017.3. I used this command to install: pip install git+https://github.com/owtf/owtf#egg=owtf

Version: 2.3b0
