### ISSUE TITLE
TypeError: argument of type 'int' is not iterable

### ISSUE THREAD

**Issue by janithmalinga** [owtf/owtf#925]
I'm getting this error message when I try to install OWTF on my latest kali linux VM

OS details
Linux kali 4.14.0-kali3-amd64 #1 SMP Debian 4.14.12-2kali2 (2018-01-11) x86_64 GNU/Linux

Error message
Traceback (most recent call last):
  File "/root/Tools/owtf/owtf/install/install.py", line 136, in <module>
    install_restricted_from_cfg(restricted_cfg)
  File "/root/Tools/owtf/owtf/install/install.py", line 85, in install_restricted_from_cfg
    install_in_directory(os.path.expanduser(cp.get(section, "directory")), cp.get(section, "command"))
  File "/usr/lib/python2.7/dist-packages/backports/configparser/__init__.py", line 811, in get
    d)
  File "/usr/lib/python2.7/dist-packages/backports/configparser/__init__.py", line 384, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "/usr/lib/python2.7/dist-packages/backports/configparser/__init__.py", line 425, in _interpolate_some
    if "%" in v:
TypeError: argument of type 'int' is not iterable

**Comment by viyatb** [comment]
Which OWTF version are you trying to install?

**Comment by janithmalinga** [comment]
Hi viyatb, 
I'm using the latest version on the github. 
#git clone https://github.com/owtf/owtf.git
