### ISSUE TITLE
Kali Linux 2018.2 Fix for psycopg2 and pip

### ISSUE THREAD

**Issue by oaldahir** [owtf/owtf#983]
When installing OWTF  2.1a, Release: Chicken Korma (Alpha) on Kali Linux 18.2 the following errors appear.

Error 1) 

Traceback (most recent call last):
  File "./owtf.py", line 13, in <module>
    from framework.core import Core
  File "/root/bin/owtf/framework/__init__.py", line 4, in <module>
    from framework.dependency_check import verify_dependencies
  File "/root/bin/owtf/framework/dependency_check.py", line 13, in <module>
    pip.get_installed_distributions()

This can be fixed by down grading to pip 9.0.3 with the following command from the kali virtual environment.

Fix 1) 

(owtf) pip install pip==9.0.3

Error 2) 

Traceback (most recent call last):
  File "../bin/owtf/owtf.py", line 258, in <module>
    main(sys.argv)
  File "../bin/owtf/owtf.py", line 219, in main
    ComponentInitialiser.initialisation_phase_1(root_dir, owtf_pid)
  File "/root/bin/owtf/framework/dependency_management/component_initialiser.py", line 57, in initialisation_phase_1
    DB()
  File "/root/bin/owtf/framework/db/db.py", line 70, in __init__
    self.create_session()
  File "/root/bin/owtf/framework/db/db.py", line 97, in create_session
    self.Session = self.CreateScopedSession()
  File "/root/bin/owtf/framework/db/db.py", line 148, in CreateScopedSession
    self.engine = self.CreateEngine(models.Base)
  File "/root/bin/owtf/framework/db/db.py", line 131, in CreateEngine
    poolclass=NullPool)
  File "/root/.virtualenvs/owtf/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 387, in create_engine
    return strategy.create(*args, **kwargs)
  File "/root/.virtualenvs/owtf/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 80, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/root/.virtualenvs/owtf/lib/python2.7/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 554, in dbapi
    import psycopg2
  File "/root/.virtualenvs/owtf/lib/python2.7/site-packages/psycopg2/__init__.py", line 50, in <module>
    from psycopg2._psycopg import (                     # noqa

This can be fixed by disabling wheel binary package with the following commands (from the virtual env)

Fix 2) 

(owtf)  pip uninstall psycopg2

(owtf) pip install --no-binary :all: psycopg2

**Comment by viyatb** [comment]
@oaldahir thanks for the report! Please use the latest master version of OWTF - `git clone -b master https://github.com/owtf/owtf; cd owtf; python setup.py install` or use the Docker image! - `docker pull owtf/owtf` and `docker run -it -p 8008:8008 -p 8009:8009 -p 8010:8010 owtf/owtf`.
