### ISSUE TITLE
Mac error

### ISSUE THREAD

**Issue by 1522402210** [owtf/owtf#995]
Mac

install OK:

```
[*] Finished!
[*] Start OWTF by running cd path/to/pentest/directory; owtf
```

but,when i used ：

```
> owtf

 _____ _ _ _ _____ _____
|     | | | |_   _|   __|
|  |  | | | | | | |   __|
|_____|_____| |_| |__|

        @owtfp
    http://owtf.org
    
[-] Loading config from: /Library/Frameworks/Python.framework/Versions/2.7/bin/data/conf/framework.cfg..
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/owtf", line 11, in <module>
    load_entry_point('owtf==2.3b0', 'console_scripts', 'owtf')()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/owtf-2.3b0-py2.7.egg/owtf/__main__.py", line 14, in main
    owtf_main(sys.argv)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/owtf-2.3b0-py2.7.egg/owtf/cli.py", line 251, in main
    ComponentInitialiser.initialisation_phase_1(root_dir, owtf_pid)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/owtf-2.3b0-py2.7.egg/owtf/dependency_management/component_initialiser.py", line 53, in initialisation_phase_1
    Config(root_dir, owtf_pid)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/owtf-2.3b0-py2.7.egg/owtf/config/config.py", line 73, in __init__
    self.load_config_from_file(self.framework_config_file_path())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/owtf-2.3b0-py2.7.egg/owtf/config/config.py", line 126, in load_config_from_file
    config_file = FileOperations.open(config_path, 'r')
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/owtf-2.3b0-py2.7.egg/owtf/utils.py", line 75, in io_error
    raise e
IOError: [Errno 2] No such file or directory: '/Library/Frameworks/Python.framework/Versions/2.7/bin/data/conf/framework.cfg'
```

**Comment by viyatb** [comment]
You are using an old OWTF release, please pull the latest code from the develop branch.
