### ISSUE TITLE
python3.6: ModuleNotFoundError: No module named 'urlparse'

### ISSUE THREAD

**Issue by blshkv** [owtf/owtf#997]
net-analyzer/owtf-2.4

```
bash $ owtf 
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/owtf/http/requester.py", line 19, in <module>
    from urllib import HTTPHandler, HTTPSHandler, HTTPRedirectHandler, ProxyHandler, build_opener, install_opener
ImportError: cannot import name 'HTTPHandler'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.6/owtf", line 11, in <module>
    load_entry_point('owtf==2.3b0', 'console_scripts', 'owtf')()
  File "/usr/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 587, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 2800, in load_entry_point
    return ep.load()
  File "/usr/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 2431, in load
    return self.resolve()
  File "/usr/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 2437, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib64/python3.6/site-packages/owtf/__main__.py", line 10, in <module>
    from owtf.cli import main as owtf_main
  File "/usr/lib64/python3.6/site-packages/owtf/cli.py", line 13, in <module>
    from owtf.core import Core
  File "/usr/lib64/python3.6/site-packages/owtf/core.py", line 21, in <module>
    from owtf.dependency_management.component_initialiser import ComponentInitialiser
  File "/usr/lib64/python3.6/site-packages/owtf/dependency_management/component_initialiser.py", line 13, in <module>
    from owtf.http.requester import Requester
  File "/usr/lib64/python3.6/site-packages/owtf/http/requester.py", line 21, in <module>
    from urlparse import urlparse
ModuleNotFoundError: No module named 'urlparse'

```

I guess it must be something similar to the code owtf-2.4/owtf/proxy/transaction_logger.py:
```
if sys.version_info[0] == 3:                                                                                               
    from urllib.parse import urlparse                                                                                      
else:                                                                                                                      
    from urlparse import urlparse
```

**Comment by viyatb** [comment]
Please use the latest OWTF from the develop branch -- OWTF no longer uses the code you referenced.
